apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: aashkajain/frontend:BUILD_NUMBER
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_YOUR_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: secrets
              key: REACT_APP_YOUR_HOSTNAME
