apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: aashkajain/backend:BUILD_NUMBER
        ports:
        - containerPort: 5000
        env:
        - name: ATLAS_URI
          valueFrom:
            secretKeyRef:
              name: secrets
              key: ATLAS_URI
